from enum import Enum

class ObjectType(Enum):
    NONE = 0
    ALARMCLOCK = 1
    APPLE = 2
    BANANA = 3
    BINOCULARS = 4
    BOWL = 5
    CAMERA = 6
    CRACKERBOX = 7
    CUP = 8
    DISKLID = 9
    EYEGLASSES = 10
    FLASHLIGHT = 11
    FRYINGPAN = 12
    GAMECONTROLLER = 13
    HAMMER = 14
    HEADPHONES = 15
    KNIFE = 16
    MOUSE = 17
    MUG = 18
    PLATE = 19
    POTTEDMEATCAN = 20
    SCISSORS = 21
    SMARTPHONE = 22
    SPHERELARGE = 23
    SPHERESMALL = 24
    STAPLER = 25
    TEAPOT = 26
    TOOTHPASTE = 27
    WATCH = 28
    WATERBOTTLE = 29
    WINEGLASS = 30

